"""
BAM Sketch Review Manager

Manages the human review flow for major sketch change proposals
generated by the agent-driven pipeline.
"""

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Optional

from .agent_review import SketchChangeProposal

logger = logging.getLogger("bam.sketch_review")

REVIEW_FILENAME = "sketch_review.json"


class SketchReviewManager:
    """Manages pending sketch change reviews for a project."""

    def __init__(self, project_dir: str):
        self.project_dir = Path(project_dir)
        self._review_path = self.project_dir / REVIEW_FILENAME

    def has_pending_review(self) -> bool:
        """Check if there is a pending sketch review."""
        review = self.get_review()
        return review is not None and review.get("status") == "pending"

    def create_review(self, proposal: SketchChangeProposal,
                      run_id: str, task_id: str) -> dict:
        """Create a new sketch review from a proposal."""
        review = {
            "status": "pending",
            "createdAt": datetime.utcnow().isoformat(),
            "decidedAt": None,
            "runId": run_id,
            "taskId": task_id,
            "proposal": proposal.to_dict(),
            "decision": None,
            "feedback": None,
        }

        with open(self._review_path, "w") as f:
            json.dump(review, f, indent=2)

        logger.info("Created sketch review for task %s (run %s)", task_id, run_id)
        return review

    def get_review(self) -> Optional[dict]:
        """Get the current sketch review, if any."""
        if not self._review_path.exists():
            return None
        with open(self._review_path, "r") as f:
            return json.load(f)

    def approve(self) -> dict:
        """Approve the pending review and register new types in the project config.

        This registers new node types into the project's color configuration
        and records new edge types — it does NOT create placeholder node
        instances in the sketch.  Real nodes/edges are created later by the
        transform stage.
        """
        review = self.get_review()
        if not review or review["status"] != "pending":
            raise ValueError("No pending review to approve")

        proposal = SketchChangeProposal.from_dict(review["proposal"])

        # Register new node types in the project config's color mapping
        self._register_types(proposal)

        # Update review status
        review["status"] = "approved"
        review["decision"] = "approved"
        review["decidedAt"] = datetime.utcnow().isoformat()

        with open(self._review_path, "w") as f:
            json.dump(review, f, indent=2)

        logger.info("Sketch review approved for task %s", review["taskId"])
        return review

    def reject(self, feedback: str = "") -> dict:
        """Reject the pending review."""
        review = self.get_review()
        if not review or review["status"] != "pending":
            raise ValueError("No pending review to reject")

        review["status"] = "rejected"
        review["decision"] = "rejected"
        review["feedback"] = feedback
        review["decidedAt"] = datetime.utcnow().isoformat()

        with open(self._review_path, "w") as f:
            json.dump(review, f, indent=2)

        logger.info("Sketch review rejected for task %s", review["taskId"])
        return review

    def show(self) -> str:
        """Return a human-readable view of the pending review."""
        review = self.get_review()
        if not review:
            return "No sketch review found."

        proposal = review["proposal"]
        lines = [
            f"=== Sketch Review ===",
            f"Status: {review['status']}",
            f"Task: {review['taskId']}",
            f"Run: {review['runId']}",
            f"Created: {review['createdAt']}",
            f"",
        ]

        if proposal.get("newNodes"):
            lines.append("New node types:")
            for n in proposal["newNodes"]:
                lines.append(f"  + {n.get('type', '?')}: {n.get('description', '')}")

        if proposal.get("newEdges"):
            lines.append("New edge types:")
            for e in proposal["newEdges"]:
                lines.append(f"  + {e.get('type', '?')}: {e.get('description', '')}")

        if proposal.get("typeChanges"):
            lines.append("Type changes:")
            for tc in proposal["typeChanges"]:
                lines.append(
                    f"  ~ {tc.get('node_id', '?')}: "
                    f"{tc.get('old_type', '?')} -> {tc.get('new_type', '?')}"
                )

        if proposal.get("rationale"):
            lines.append(f"\nRationale: {proposal['rationale']}")

        if review.get("feedback"):
            lines.append(f"\nFeedback: {review['feedback']}")

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _register_types(self, proposal: SketchChangeProposal) -> None:
        """Register proposed node/edge types in the project config.

        New node types are added to the ``default`` color in
        ``storage.colors`` so that the color layer can route them.
        New edge types are recorded in ``storage.registered_edge_types``
        for documentation / validation purposes.

        This intentionally does NOT create placeholder nodes or edges in
        the sketch — real instances are created by the transform stage.
        """
        config_path = self.project_dir / "project.json"
        if not config_path.exists():
            logger.warning("project.json not found — skipping type registration")
            return

        with open(config_path, "r") as f:
            config = json.load(f)

        storage = config.setdefault("storage", {})
        colors = storage.setdefault("colors", {})
        registered_edge_types = storage.setdefault("registered_edge_types", [])

        # Determine the target color for new node types.
        # Use the color specified in the proposal, or fall back to "default".
        for node_spec in proposal.new_nodes:
            node_type = node_spec.get("type")
            if not node_type:
                continue
            target_color = node_spec.get("color", "default")
            color_def = colors.setdefault(target_color, {
                "description": target_color,
                "node_types": [],
            })
            type_list = color_def.setdefault("node_types", [])
            if node_type not in type_list:
                type_list.append(node_type)
                logger.info("Registered node type '%s' in color '%s'",
                            node_type, target_color)

        for edge_spec in proposal.new_edges:
            edge_type = edge_spec.get("type")
            if edge_type and edge_type not in registered_edge_types:
                registered_edge_types.append(edge_type)
                logger.info("Registered edge type '%s'", edge_type)

        with open(config_path, "w") as f:
            json.dump(config, f, indent=2)
